#include "compositor_config.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <android/log.h>

#define LOG_TAG "Config"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

// 全局配置管理器
static struct config_manager g_config = {0};

// 内部函数声明
static struct config_item* config_find_item(const char* name);
static struct config_item* config_create_item(const char* name, config_type_t type);
static void config_destroy_item(struct config_item* item);
static int config_parse_line(const char* line);
static int config_write_item(FILE* file, struct config_item* item);

// 初始化配置管理器
int config_init(const char* config_file) {
    if (g_config.loaded) {
        LOGE("Config manager already initialized");
        return -1;
    }
    
    if (!config_file) {
        LOGE("Invalid config file path");
        return -1;
    }
    
    memset(&g_config, 0, sizeof(g_config));
    strncpy(g_config.config_file, config_file, sizeof(g_config.config_file) - 1);
    g_config.config_file[sizeof(g_config.config_file) - 1] = '\0';
    g_config.auto_save = true;
    
    LOGI("Config manager initialized with file: %s", config_file);
    return 0;
}

// 销毁配置管理器
void config_destroy(void) {
    if (!g_config.loaded) {
        return;
    }
    
    // 自动保存配置
    if (g_config.auto_save) {
        config_save();
    }
    
    // 销毁所有配置项
    struct config_item* item = g_config.items;
    while (item) {
        struct config_item* next = item->next;
        config_destroy_item(item);
        item = next;
    }
    
    memset(&g_config, 0, sizeof(g_config));
    LOGI("Config manager destroyed");
}

// 从文件加载配置
int config_load(void) {
    if (!g_config.config_file[0]) {
        LOGE("Config file not set");
        return -1;
    }
    
    FILE* file = fopen(g_config.config_file, "r");
    if (!file) {
        LOGI("Config file not found, using defaults");
        return 0;
    }
    
    char line[512];
    int line_num = 0;
    int error_count = 0;
    
    while (fgets(line, sizeof(line), file)) {
        line_num++;
        
        // 跳过空行和注释
        if (line[0] == '\n' || line[0] == '#') {
            continue;
        }
        
        // 解析配置行
        if (config_parse_line(line) != 0) {
            LOGE("Error parsing line %d: %s", line_num, line);
            error_count++;
        }
    }
    
    fclose(file);
    
    g_config.loaded = true;
    
    if (error_count > 0) {
        LOGE("Loaded config with %d errors", error_count);
        return -1;
    } else {
        LOGI("Config loaded successfully");
        return 0;
    }
}

// 保存配置到文件
int config_save(void) {
    if (!g_config.config_file[0]) {
        LOGE("Config file not set");
        return -1;
    }
    
    FILE* file = fopen(g_config.config_file, "w");
    if (!file) {
        LOGE("Failed to open config file for writing");
        return -1;
    }
    
    // 写入文件头
    fprintf(file, "# Compositor Configuration File\n");
    fprintf(file, "# This file is automatically generated\n\n");
    
    // 写入所有配置项
    struct config_item* item = g_config.items;
    while (item) {
        if (config_write_item(file, item) != 0) {
            LOGE("Failed to write config item: %s", item->name);
            fclose(file);
            return -1;
        }
        item = item->next;
    }
    
    fclose(file);
    LOGI("Config saved successfully");
    return 0;
}

// 设置是否自动保存
void config_set_auto_save(bool auto_save) {
    g_config.auto_save = auto_save;
    LOGI("Auto save %s", auto_save ? "enabled" : "disabled");
}

// 注册整数配置项
int config_register_int(const char* name, int default_val) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    // 检查是否已存在
    if (config_find_item(name)) {
        LOGE("Config item already exists: %s", name);
        return -1;
    }
    
    // 创建新配置项
    struct config_item* item = config_create_item(name, CONFIG_TYPE_INT);
    if (!item) {
        LOGE("Failed to create config item: %s", name);
        return -1;
    }
    
    item->value.int_val = default_val;
    item->default_value.int_default = default_val;
    
    LOGD("Registered int config: %s = %d", name, default_val);
    return 0;
}

// 注册浮点数配置项
int config_register_float(const char* name, float default_val) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    // 检查是否已存在
    if (config_find_item(name)) {
        LOGE("Config item already exists: %s", name);
        return -1;
    }
    
    // 创建新配置项
    struct config_item* item = config_create_item(name, CONFIG_TYPE_FLOAT);
    if (!item) {
        LOGE("Failed to create config item: %s", name);
        return -1;
    }
    
    item->value.float_val = default_val;
    item->default_value.float_default = default_val;
    
    LOGD("Registered float config: %s = %f", name, default_val);
    return 0;
}

// 注册布尔配置项
int config_register_bool(const char* name, bool default_val) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    // 检查是否已存在
    if (config_find_item(name)) {
        LOGE("Config item already exists: %s", name);
        return -1;
    }
    
    // 创建新配置项
    struct config_item* item = config_create_item(name, CONFIG_TYPE_BOOL);
    if (!item) {
        LOGE("Failed to create config item: %s", name);
        return -1;
    }
    
    item->value.bool_val = default_val;
    item->default_value.bool_default = default_val;
    
    LOGD("Registered bool config: %s = %s", name, default_val ? "true" : "false");
    return 0;
}

// 注册字符串配置项
int config_register_string(const char* name, const char* default_val) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    // 检查是否已存在
    if (config_find_item(name)) {
        LOGE("Config item already exists: %s", name);
        return -1;
    }
    
    // 创建新配置项
    struct config_item* item = config_create_item(name, CONFIG_TYPE_STRING);
    if (!item) {
        LOGE("Failed to create config item: %s", name);
        return -1;
    }
    
    if (default_val) {
        item->value.string_val = strdup(default_val);
        item->default_value.string_default = strdup(default_val);
    } else {
        item->value.string_val = strdup("");
        item->default_value.string_default = strdup("");
    }
    
    LOGD("Registered string config: %s = %s", name, default_val ? default_val : "");
    return 0;
}

// 获取整数配置值
int config_get_int(const char* name, int* value) {
    if (!name || !value) {
        LOGE("Invalid parameters");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_INT) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    *value = item->value.int_val;
    return 0;
}

// 获取浮点数配置值
int config_get_float(const char* name, float* value) {
    if (!name || !value) {
        LOGE("Invalid parameters");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_FLOAT) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    *value = item->value.float_val;
    return 0;
}

// 获取布尔配置值
int config_get_bool(const char* name, bool* value) {
    if (!name || !value) {
        LOGE("Invalid parameters");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_BOOL) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    *value = item->value.bool_val;
    return 0;
}

// 获取字符串配置值
int config_get_string(const char* name, char* value, size_t max_len) {
    if (!name || !value || max_len == 0) {
        LOGE("Invalid parameters");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_STRING) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    strncpy(value, item->value.string_val, max_len - 1);
    value[max_len - 1] = '\0';
    return 0;
}

// 设置整数配置值
int config_set_int(const char* name, int value) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_INT) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    item->value.int_val = value;
    item->modified = (value != item->default_value.int_default);
    
    // 自动保存
    if (g_config.auto_save) {
        config_save();
    }
    
    LOGD("Set int config: %s = %d", name, value);
    return 0;
}

// 设置浮点数配置值
int config_set_float(const char* name, float value) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_FLOAT) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    item->value.float_val = value;
    item->modified = (value != item->default_value.float_default);
    
    // 自动保存
    if (g_config.auto_save) {
        config_save();
    }
    
    LOGD("Set float config: %s = %f", name, value);
    return 0;
}

// 设置布尔配置值
int config_set_bool(const char* name, bool value) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_BOOL) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    item->value.bool_val = value;
    item->modified = (value != item->default_value.bool_default);
    
    // 自动保存
    if (g_config.auto_save) {
        config_save();
    }
    
    LOGD("Set bool config: %s = %s", name, value ? "true" : "false");
    return 0;
}

// 设置字符串配置值
int config_set_string(const char* name, const char* value) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item || item->type != CONFIG_TYPE_STRING) {
        LOGE("Config item not found or wrong type: %s", name);
        return -1;
    }
    
    // 释放旧值
    if (item->value.string_val) {
        free(item->value.string_val);
    }
    
    // 设置新值
    item->value.string_val = value ? strdup(value) : strdup("");
    item->modified = (strcmp(item->value.string_val, item->default_value.string_default) != 0);
    
    // 自动保存
    if (g_config.auto_save) {
        config_save();
    }
    
    LOGD("Set string config: %s = %s", name, value ? value : "");
    return 0;
}

// 重置配置项为默认值
int config_reset(const char* name) {
    if (!name) {
        LOGE("Invalid config name");
        return -1;
    }
    
    struct config_item* item = config_find_item(name);
    if (!item) {
        LOGE("Config item not found: %s", name);
        return -1;
    }
    
    switch (item->type) {
        case CONFIG_TYPE_INT:
            item->value.int_val = item->default_value.int_default;
            break;
        case CONFIG_TYPE_FLOAT:
            item->value.float_val = item->default_value.float_default;
            break;
        case CONFIG_TYPE_BOOL:
            item->value.bool_val = item->default_value.bool_default;
            break;
        case CONFIG_TYPE_STRING:
            if (item->value.string_val) {
                free(item->value.string_val);
            }
            item->value.string_val = strdup(item->default_value.string_default);
            break;
    }
    
    item->modified = false;
    
    // 自动保存
    if (g_config.auto_save) {
        config_save();
    }
    
    LOGD("Reset config: %s", name);
    return 0;
}

// 重置所有配置项为默认值
void config_reset_all(void) {
    struct config_item* item = g_config.items;
    while (item) {
        switch (item->type) {
            case CONFIG_TYPE_INT:
                item->value.int_val = item->default_value.int_default;
                break;
            case CONFIG_TYPE_FLOAT:
                item->value.float_val = item->default_value.float_default;
                break;
            case CONFIG_TYPE_BOOL:
                item->value.bool_val = item->default_value.bool_default;
                break;
            case CONFIG_TYPE_STRING:
                if (item->value.string_val) {
                    free(item->value.string_val);
                }
                item->value.string_val = strdup(item->default_value.string_default);
                break;
        }
        
        item->modified = false;
        item = item->next;
    }
    
    // 自动保存
    if (g_config.auto_save) {
        config_save();
    }
    
    LOGI("Reset all configs to defaults");
}

// 检查配置项是否存在
bool config_exists(const char* name) {
    return config_find_item(name) != NULL;
}

// 检查配置项是否已修改
bool config_is_modified(const char* name) {
    struct config_item* item = config_find_item(name);
    return item ? item->modified : false;
}

// 应用配置更改
int config_apply(void) {
    // 在实际实现中，这里会通知各个模块配置已更改
    // 目前简化为直接保存
    return config_save();
}

// 打印所有配置项
void config_print_all(void) {
    LOGI("Current configuration:");
    
    struct config_item* item = g_config.items;
    while (item) {
        switch (item->type) {
            case CONFIG_TYPE_INT:
                LOGI("  %s = %d%s", item->name, item->value.int_val, 
                     item->modified ? " (modified)" : "");
                break;
            case CONFIG_TYPE_FLOAT:
                LOGI("  %s = %f%s", item->name, item->value.float_val, 
                     item->modified ? " (modified)" : "");
                break;
            case CONFIG_TYPE_BOOL:
                LOGI("  %s = %s%s", item->name, item->value.bool_val ? "true" : "false", 
                     item->modified ? " (modified)" : "");
                break;
            case CONFIG_TYPE_STRING:
                LOGI("  %s = \"%s\"%s", item->name, item->value.string_val, 
                     item->modified ? " (modified)" : "");
                break;
        }
        item = item->next;
    }
}

// 内部函数：查找配置项
static struct config_item* config_find_item(const char* name) {
    if (!name) return NULL;
    
    struct config_item* item = g_config.items;
    while (item) {
        if (strcmp(item->name, name) == 0) {
            return item;
        }
        item = item->next;
    }
    
    return NULL;
}

// 内部函数：创建配置项
static struct config_item* config_create_item(const char* name, config_type_t type) {
    if (!name) return NULL;
    
    struct config_item* item = (struct config_item*)calloc(1, sizeof(struct config_item));
    if (!item) {
        return NULL;
    }
    
    strncpy(item->name, name, sizeof(item->name) - 1);
    item->name[sizeof(item->name) - 1] = '\0';
    item->type = type;
    
    // 添加到链表
    item->next = g_config.items;
    g_config.items = item;
    
    return item;
}

// 内部函数：销毁配置项
static void config_destroy_item(struct config_item* item) {
    if (!item) return;
    
    // 释放字符串值
    if (item->type == CONFIG_TYPE_STRING) {
        if (item->value.string_val) {
            free(item->value.string_val);
        }
        if (item->default_value.string_default) {
            free(item->default_value.string_default);
        }
    }
    
    free(item);
}

// 内部函数：解析配置行
static int config_parse_line(const char* line) {
    if (!line) return -1;
    
    // 简化实现：使用strtok解析
    char* line_copy = strdup(line);
    if (!line_copy) return -1;
    
    // 移除换行符
    char* newline = strchr(line_copy, '\n');
    if (newline) *newline = '\0';
    
    // 分割键值对
    char* eq = strchr(line_copy, '=');
    if (!eq) {
        free(line_copy);
        return -1;
    }
    
    *eq = '\0';
    char* name = line_copy;
    char* value = eq + 1;
    
    // 去除空格
    while (*name == ' ') name++;
    char* name_end = name + strlen(name) - 1;
    while (name_end > name && *name_end == ' ') {
        *name_end = '\0';
        name_end--;
    }
    
    while (*value == ' ') value++;
    char* value_end = value + strlen(value) - 1;
    while (value_end > value && *value_end == ' ') {
        *value_end = '\0';
        value_end--;
    }
    
    // 查找配置项
    struct config_item* item = config_find_item(name);
    if (!item) {
        free(line_copy);
        return -1;
    }
    
    // 设置值
    int result = 0;
    switch (item->type) {
        case CONFIG_TYPE_INT:
            item->value.int_val = atoi(value);
            item->modified = (item->value.int_val != item->default_value.int_default);
            break;
        case CONFIG_TYPE_FLOAT:
            item->value.float_val = atof(value);
            item->modified = (item->value.float_val != item->default_value.float_default);
            break;
        case CONFIG_TYPE_BOOL:
            if (strcmp(value, "